spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mpick?useUnicode=true&characterEncoding=utf8
    username: root
    password: ${database.password}

  jpa:
    hibernate:
#      ddl-auto: none 나중에 적용할 값
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
