spring:
  mail:
    host: ${email.host}
    port: ${email.port}
    username: ${email.id}  # 이메일 전송시 사용할 계정
    password: ${email.password}
    properties: # 이메일 추가 속성
      mail:
        smtp:
          auth: true  # Gmail SMTP 서버는 인증을 요구하기 때문에 true
          starttls:
            enable: true  # SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정
            required: true
          connectiontimeout: 5000 # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간
          timeout: 5000 # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간 (서버에서 응답이 오지 않는 경우 대기 시간을 제한)
          writetimeout: 5000  # 클라이언트가 작업을 완료하는데 대기해야 하는 시간 (이메일을 SMTP 서버로 전송하는 데 걸리는 시간을 제한)
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

