logging:
  file:
    name: ./logs/mpick.log
  level:
    root: info
    com.windows33.com.windows33.cavendish: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        security: warn