# 공통 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

--- # local 설정
spring:
  config:
    activate:
      on-profile: "db-local"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 보기 좋게 표시
        show_sql: true    # SQL 쿼리 확인

  datasource:
    url: jdbc:mysql://localhost:3306/mpick
    username: root
    password: root

  sql:
    init:
      encoding: UTF-8

--- # prod 설정
spring:
  config:
    activate:
      on-profile: "db-prod"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false # SQL 쿼리 보기 좋게 표시 X
        show_sql: false   # SQL 쿼리 확인 X

  datasource:
    url: jdbc:mariadb://j9c105.p.ssafy.io:3306/s09p22c105
    username: root
    password: ssafy

  sql:
    init:
      encoding: UTF-8