
spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local

      prod:
        - db-prod

    include:
      - db
      - swagger

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher