springdoc:
  packages-to-scan: com.k9c202.mpick
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api/swagger-ui # swagger HTML 문서 경로 (기본값: /swagger-ui.html)
    tags-sorter: alpha # 태그 정렬 기준
    operations-sorter: alpha # api 정렬 기준 (alpha: 알파벳 오름차순, method:http method순)
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true