logging:
  file:
    name: ./logs/mpick.log
  level:
    root: info
    com.k9c202.mpick: debug  # error - warning - info - debug - trace
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        security: warn