spring:
  profiles:
    include:
      - db
      - swagger
      - log
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 5000

jwt:
  # 암호화 키 (https://www.base64encode.org/ 사용해서 임의의 값 넣음)
  secret: YXNkZm53azNuc2Rsd25kbGZvbmMsdjsybzM0MDk2anNsZG52bHNsZGY7ZCdmYQ==YXNkZm53azNuc2Rsd25kbGZvbmMsdjsybzM0MDk2anNsZG52bHNsZGY7ZCdmYQ==
  # 유효기간 (1일 설정)
  token-validity-in-seconds: 86400