spring:
  profiles:
    include:
      - db
      - swagger
      - log
      - email
      - s3

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # redis 설정
  data:
    redis:
      host:
        redis
      port:
        ${redis.port}


# Spring 포트번호 5000으로 설정
server:
  port: 5000

# jwt
jwt:
  # 암호화 키 (https://www.base64encode.org/ 사용해서 임의의 값 넣음)
  secret: ${jwt.secret}
  # 유효기간 (1일 설정)
  token-validity-in-seconds: 86400

