version: "2.4"

services:

  spring:
    build: ./backend/mpick
    ports:
      - "5000:5000"
    cpus: 0.2
    mem_limit: 2000m
  
  front:
    build: ./frontend/mpick
    ports:
      - "3000:3000"

  python:
    build: ./recommend
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    container_name: redis
    ports: 
      - "6379:6379"
  